"""baseline: pre-phase-2 six table schema

Represents the schema exactly as it existed at the end of Phase 1 (Lead,
LeadBatch, LeadScore, AIOutput, IntegrationPush, WorkflowEvent -- no
provenance, no output/review identity). Generated by autogenerating against
the pre-Phase-2 models (temporarily restored via `git stash` for this one
generation step) so it reflects real model state, not a hand-transcription.

This is the revision an EXISTING database created by the old
`app.core.init_db.init_db()` (`Base.metadata.create_all`) path should be
stamped to -- see scripts/verify_baseline_schema.py, which checks a target
database's actual schema against this revision's expectations before
allowing that stamp. Never stamp head directly on an existing database.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-22

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('processed_leads', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cleaned_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['lead_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_batch_id'), 'leads', ['batch_id'], unique=False)
    op.create_index(op.f('ix_leads_company_name'), 'leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_leads_contact_email'), 'leads', ['contact_email'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('ai_outputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('output_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_outputs_lead_id'), 'ai_outputs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_ai_outputs_output_type'), 'ai_outputs', ['output_type'], unique=False)
    op.create_table('integration_pushes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('integration_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_pushes_created_at'), 'integration_pushes', ['created_at'], unique=False)
    op.create_index(op.f('ix_integration_pushes_integration_type'), 'integration_pushes', ['integration_type'], unique=False)
    op.create_index(op.f('ix_integration_pushes_lead_id'), 'integration_pushes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_integration_pushes_status'), 'integration_pushes', ['status'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=True)
    op.create_index(op.f('ix_lead_scores_priority'), 'lead_scores', ['priority'], unique=False)
    op.create_index(op.f('ix_lead_scores_total_score'), 'lead_scores', ['total_score'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['lead_batches.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_batch_id'), 'workflow_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_created_at'), 'workflow_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_events_event_type'), 'workflow_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_workflow_events_lead_id'), 'workflow_events', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_lead_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_event_type'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_created_at'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_batch_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_lead_scores_total_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_priority'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_integration_pushes_status'), table_name='integration_pushes')
    op.drop_index(op.f('ix_integration_pushes_lead_id'), table_name='integration_pushes')
    op.drop_index(op.f('ix_integration_pushes_integration_type'), table_name='integration_pushes')
    op.drop_index(op.f('ix_integration_pushes_created_at'), table_name='integration_pushes')
    op.drop_table('integration_pushes')
    op.drop_index(op.f('ix_ai_outputs_output_type'), table_name='ai_outputs')
    op.drop_index(op.f('ix_ai_outputs_lead_id'), table_name='ai_outputs')
    op.drop_table('ai_outputs')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_batch_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('lead_batches')
    # ### end Alembic commands ###
