"""pdl identity confidence and import idempotency constraints

Phase 3 of the GTMFlow upgrade (see docs/engineering-log/decisions.md). Additive
only -- does not touch 0001_baseline or 0002_provenance.

  - company_identities.identity_confidence: "source_id" | "fingerprint",
    honestly recording whether a CompanyIdentity's source_record_id came
    from the source's own id field or a derived fingerprint (Part D.2).
  - uq_company_identities_snapshot_source_record and
    uq_leads_snapshot_source_record: the actual idempotent-reimport
    guarantee (Part D.7) -- re-running the importer against the same
    SourceSnapshot can never create a second CompanyIdentity/Lead for a
    company already imported; the database enforces it, not just
    application-level find-or-create logic. NULLs (every CSV/demo lead,
    which never populate these columns) remain unrestricted under both
    constraints -- verified empirically (see the Phase 3 handoff).
  - import_runs.logical_key: an indexed (not unique) fingerprint of the
    curation configuration that produced a given ImportRun, for reporting
    "was this exact selection attempted before" -- not itself the
    anti-duplication mechanism (that's the two constraints above).

Revision ID: 0003_pdl_identity
Revises: 0002_provenance
Create Date: 2026-09-22

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_pdl_identity'
down_revision: Union[str, Sequence[str], None] = '0002_provenance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_identities', sa.Column('identity_confidence', sa.String(length=16), nullable=True))
    op.create_unique_constraint('uq_company_identities_snapshot_source_record', 'company_identities', ['source_snapshot_id', 'source_record_id'])
    op.add_column('import_runs', sa.Column('logical_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_import_runs_logical_key'), 'import_runs', ['logical_key'], unique=False)
    op.create_unique_constraint('uq_leads_snapshot_source_record', 'leads', ['source_snapshot_id', 'source_record_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leads_snapshot_source_record', 'leads', type_='unique')
    op.drop_index(op.f('ix_import_runs_logical_key'), table_name='import_runs')
    op.drop_column('import_runs', 'logical_key')
    op.drop_constraint('uq_company_identities_snapshot_source_record', 'company_identities', type_='unique')
    op.drop_column('company_identities', 'identity_confidence')
    # ### end Alembic commands ###
