"""csv upload content hash for retry resume

Phase 4 closeout Part A.4 (carried forward from Phase 3). Additive only --
does not touch 0001-0004. Adds `lead_batches.upload_content_hash` (sha256
of the uploaded file's bytes, CSV-upload batches only, NULL for PDL/demo
batches). Lets `POST /api/batches/upload` detect "this is a retry of an
upload that previously left a batch partial" by matching the new file's
hash against an existing `status='partial'` batch, and resume (skip
already-committed rows) instead of creating a second batch and
re-inserting rows that already landed. See app/api/batches.py.

Revision ID: 0005_csv_retry
Revises: 0004_logical_key
Create Date: 2026-09-22

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_csv_retry'
down_revision: Union[str, Sequence[str], None] = '0004_logical_key'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_batches', sa.Column('upload_content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_lead_batches_upload_content_hash'), 'lead_batches', ['upload_content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_batches_upload_content_hash'), table_name='lead_batches')
    op.drop_column('lead_batches', 'upload_content_hash')
    # ### end Alembic commands ###
